asn5: asn5.o read_bignum.o write_bignum.o get_bignum.o put_bignum.o add_bignum.o stringio.o iofunc.o
	gcc -o asn5 $^

%.o: %.s
	gcc -c $<

%.s: %.m
	-rm $@
	m4 $< > $@

realclean: clean
	-rm asn5

clean:
	-rm asn5.s read_bignum.s write_bignum.s get_bignum.s put_bignum.s add_bignum.s
	-rm asn5.o read_bignum.o write_bignum.o get_bignum.o put_bignum.o add_bignum.o stringio.o

