################################################################################
#
# Makefile
# 
# Author: Jeff Shantz
#
# Targets:
#
#   asn5:  Build asn5 executable
#   debug: Build asn5 executable with debugging symbols
#   clean: Remove all intermediary files
#   realclean: Remove intermediary and executable files
#
################################################################################

CC=gcc
MP=m4
CFLAGS=-c
LFLAGS=-o
DFLAGS=-g $(LFLAGS)
OBJECTS=asn5.o \
        read_bignum.o \
        write_bignum.o \
        get_bignum.o \
        put_bignum.o \
        add_bignum.o \
        stringio.o
        
asn5: $(OBJECTS) iofunc.o
	$(CC) $(LFLAGS) asn5 $^

debug: $(OBJECTS) iofunc.o
	$(CC) $(DFLAGS) asn5 $^
	
%.o: %.s
	$(CC) $(CFLAGS) $<

%.s: %.m
	-rm $@
	$(MP) $< > $@

realclean: clean
	-rm asn5

clean:
	-rm asn5.s read_bignum.s write_bignum.s get_bignum.s put_bignum.s add_bignum.s
	-rm $(OBJECTS)
	

