asn5: asn5.o stringio.o iofunc.o
	gcc -o asn5 asn5.o stringio.o iofunc.o

stringio.o: stringio.s
	gcc -c stringio.s

asn5.o: asn5.s
	gcc -c asn5.s

asn5.s:	asn5.m
	-rm asn5.s
	m4 asn5.m > asn5.s

clean:
	rm asn5.s
	rm asn5.o stringio.o
