CC=gcc
MP=m4
CFLAGS=-c
LFLAGS=-o

asn5: asn5.o stringio.o iofunc.o
	$(CC) $(LFLAGS) asn5 asn5.o stringio.o iofunc.o

stringio.o: stringio.s
	$(CC) $(CFLAGS) stringio.s

asn5.o: asn5.s
	$(CC) $(CFLAGS) asn5.s

asn5.s:	asn5.m
	-rm asn5.s
	$(MP) asn5.m > asn5.s

realclean: clean
	-rm asn5

clean:
	-rm asn5.s
	-rm asn5.o stringio.o
